<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Array-creation" data-toc-modified-id="Array-creation-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Array creation</a></span></li></ul></div>

In [1]:
import pandas as pd

In [2]:
import numpy as np

## Array creation

In [3]:
a = np.array([1,2,3,4,5])

In [4]:
a

array([1, 2, 3, 4, 5])

In [5]:
type(a)

numpy.ndarray

In [7]:
a.shape

(5,)

In [8]:
a.dtype

dtype('int64')

In [10]:
b = np.array([1,2,3,4,5], dtype='int32')

In [11]:
b.dtype

dtype('int32')

In [12]:
c = np.zeros((5,5))

In [13]:
c

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
c.shape

(5, 5)

In [15]:
np.random.randint(1,100,(10,))

array([ 4, 80,  1, 21, 79, 37, 30, 57, 67, 98])

In [19]:
np.random.rand(5,5)

array([[0.28159011, 0.33497483, 0.96184007, 0.00257186, 0.28154182],
       [0.89229   , 0.33104269, 0.01843872, 0.96233376, 0.02795333],
       [0.06730372, 0.56557495, 0.42741355, 0.42252412, 0.03568911],
       [0.93627025, 0.327342  , 0.10113354, 0.28384184, 0.5909987 ],
       [0.51843839, 0.95973522, 0.8616839 , 0.8879265 , 0.85893929]])

In [20]:
np.random.randn(10,2)

array([[ 1.57009987,  0.9021482 ],
       [ 0.32185959, -1.9573131 ],
       [ 1.31285366, -0.18423305],
       [-0.32319244, -0.30411833],
       [-0.13098357,  0.6365151 ],
       [ 1.11735471, -0.53307329],
       [ 0.24677688, -2.20709426],
       [ 0.01358907, -0.7591014 ],
       [-2.47333732,  0.83061694],
       [ 0.36945184, -1.1308731 ]])

In [27]:
np.ones((5,5))*3 + np.eye(5,5)*2

array([[5., 3., 3., 3., 3.],
       [3., 5., 3., 3., 3.],
       [3., 3., 5., 3., 3.],
       [3., 3., 3., 5., 3.],
       [3., 3., 3., 3., 5.]])

In [84]:
np.ones((5,5)).dtype

dtype('float64')

In [31]:
a = np.ones((5,5))

In [34]:
a = np.ones((5,5)) + np.eye(5,5)

In [66]:
a

array([[2., 2., 2., 1., 1.],
       [1., 4., 2., 1., 1.],
       [1., 2., 4., 1., 1.],
       [1., 1., 1., 2., 1.],
       [1., 1., 1., 1., 2.]])

In [65]:
a[0:3]

array([[2., 2., 2., 1., 1.],
       [1., 4., 2., 1., 1.],
       [1., 2., 4., 1., 1.]])

In [64]:
a[0:3][0]

array([2., 2., 2., 1., 1.])

In [70]:
a[0:3,:]

array([[2., 2., 2., 1., 1.],
       [1., 4., 2., 1., 1.],
       [1., 2., 4., 1., 1.]])

In [42]:
a[0:3,1:3] = a[0:3,1:3] * 2

In [83]:
a.dtype

dtype('float64')

In [82]:
np.vstack((a,a,a))

array([[2., 2., 2., 1., 1.],
       [1., 4., 2., 1., 1.],
       [1., 2., 4., 1., 1.],
       [1., 1., 1., 2., 1.],
       [1., 1., 1., 1., 2.],
       [2., 2., 2., 1., 1.],
       [1., 4., 2., 1., 1.],
       [1., 2., 4., 1., 1.],
       [1., 1., 1., 2., 1.],
       [1., 1., 1., 1., 2.],
       [2., 2., 2., 1., 1.],
       [1., 4., 2., 1., 1.],
       [1., 2., 4., 1., 1.],
       [1., 1., 1., 2., 1.],
       [1., 1., 1., 1., 2.]])

In [71]:
mat = np.random.randint(0,10, (2,3,3))

In [72]:
mat

array([[[2, 1, 3],
        [1, 4, 7],
        [2, 7, 0]],

       [[1, 8, 8],
        [9, 9, 4],
        [7, 2, 4]]])

In [73]:
mat[:,:,1]

array([[1, 4, 7],
       [8, 9, 2]])

In [74]:
mat[:,2,:]

array([[2, 7, 0],
       [7, 2, 4]])

In [79]:
mat[0]

array([[2, 1, 3],
       [1, 4, 7],
       [2, 7, 0]])

In [80]:
mat.dtype

dtype('int64')

In [87]:
mat

array([[[2, 1, 3],
        [1, 4, 7],
        [2, 7, 0]],

       [[1, 8, 8],
        [9, 9, 4],
        [7, 2, 4]]])

In [89]:
mat[0].mean()

3.0

In [104]:
mat.shape

(2, 3, 3)

In [106]:
np.savetxt('mat.csv', mat[0])

In [107]:
np.genfromtxt('mat.csv')

array([[2., 1., 3.],
       [1., 4., 7.],
       [2., 7., 0.]])

In [108]:
import pickle

In [109]:
with open('mi_matriz.mat','wb') as f:
    pickle.dump(mat,f)

In [112]:
with open('mi_matriz.mat','rb') as f:
    mat2 = pickle.load(f)

In [113]:
mat2

array([[[2, 1, 3],
        [1, 4, 7],
        [2, 7, 0]],

       [[1, 8, 8],
        [9, 9, 4],
        [7, 2, 4]]])

In [114]:
from urllib.request import urlopen
import json

response = urlopen("https://data.nasa.gov/resource/y77d-th95.json")
json_data = response.read().decode('utf-8', 'replace')

In [115]:
response

In [116]:
import requests

In [118]:
resp = requests.get("https://data.nasa.gov/resource/y77d-th95.json")

In [139]:
json_data = resp.text

In [124]:
import json

In [126]:
asteroides = json.loads(resp.text)

In [128]:
type(asteroides)

list

In [130]:
asteroides[0]['name']

'Aachen'

In [131]:
asteroides[0]

{'name': 'Aachen',
 'id': '1',
 'nametype': 'Valid',
 'recclass': 'L5',
 'mass': '21',
 'fall': 'Fell',
 'year': '1880-01-01T00:00:00.000',
 'reclat': '50.775000',
 'reclong': '6.083330',
 'geolocation': {'type': 'Point', 'coordinates': [6.08333, 50.775]}}

In [132]:
json.dumps(asteroides[0])

'{"name": "Aachen", "id": "1", "nametype": "Valid", "recclass": "L5", "mass": "21", "fall": "Fell", "year": "1880-01-01T00:00:00.000", "reclat": "50.775000", "reclong": "6.083330", "geolocation": {"type": "Point", "coordinates": [6.08333, 50.775]}}'

In [145]:
df = pd.read_json(resp.text)

In [150]:
df.to_json('asteroides.json', orient='records')

In [144]:
pd.json_normalize(json.loads(resp.text))

name     id nametype               recclass    mass  fall  \
0       Aachen      1    Valid                     L5      21  Fell   
1       Aarhus      2    Valid                     H6     720  Fell   
2         Abee      6    Valid                    EH4  107000  Fell   
3     Acapulco     10    Valid            Acapulcoite    1914  Fell   
4      Achiras    370    Valid                     L6     780  Fell   
..         ...    ...      ...                    ...     ...   ...   
995   Tirupati  24009    Valid                     H6     230  Fell   
996    Tissint  54823    Valid  Martian (shergottite)    7000  Fell   
997      Tjabe  24011    Valid                     H6   20000  Fell   
998   Tjerebon  24012    Valid                     L5   16500  Fell   
999  Tomakovka  24019    Valid                    LL6     600  Fell   

                        year      reclat      reclong geolocation.type  \
0    1880-01-01T00:00:00.000   50.775000     6.083330            Point   
1    1951-01-01T00:00:00.000   56.183330    10.233330            Point   
2    1952-01-01T00:00:00.000   54.216670  -113.000000            Point   
3    1976-01-01T00:00:00.000   16.883330   -99.900000            Point   
4    1902-01-01T00:00:00.000  -33.166670   -64.950000            Point   
..                       ...         ...          ...              ...   
995  1934-01-01T00:00:00.000   13.633330    79.416670            Point   
996  2011-01-01T00:00:00.000   29.481950    -7.611230            Point   
997  1869-01-01T00:00:00.000   -7.083330   111.533330            Point   
998  1922-01-01T00:00:00.000   -6.666670   106.583330            Point   
999  1905-01-01T00:00:00.000   47.850000    34.766670            Point   

    geolocation.coordinates :@computed_region_cbhk_fwbd  \
0         [6.08333, 50.775]                         NaN   
1      [10.23333, 56.18333]                         NaN   
2          [-113, 54.21667]                         NaN   
3         [-99.9, 16.88333]                         NaN   
4       [-64.95, -33.16667]                         NaN   
..                      ...                         ...   
995    [79.41667, 13.63333]                         NaN   
996    [-7.61123, 29.48195]                         NaN   
997   [111.53333, -7.08333]                         NaN   
998   [106.58333, -6.66667]                         NaN   
999       [34.76667, 47.85]                         NaN   

    :@computed_region_nnqa_25f4  
0                           NaN  
1                           NaN  
2                           NaN  
3                           NaN  
4                           NaN  
..                          ...  
995                         NaN  
996                         NaN  
997                         NaN  
998                         NaN  
999                         NaN  

[1000 rows x 13 columns]

In [153]:
import string

In [154]:
dir(string)

['Formatter',
 'Template',
 '_ChainMap',
 '_TemplateMetaclass',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_re',
 '_string',
 'ascii_letters',
 'ascii_lowercase',
 'ascii_uppercase',
 'capwords',
 'digits',
 'hexdigits',
 'octdigits',
 'printable',
 'punctuation',
 'whitespace']

In [164]:
letras = string.ascii_uppercase[:10]

In [167]:
list(string.ascii_uppercase[:10])

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [163]:
pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/00244/fertility_Diagnosis.txt', names=[a for a in string.ascii_uppercase[:10]])

A     B  C  D  E  F    G  H     I  J
0  -0.33  0.69  0  1  1  0  0.8  0  0.88  N
1  -0.33  0.94  1  0  1  0  0.8  1  0.31  O
2  -0.33  0.50  1  0  0  0  1.0 -1  0.50  N
3  -0.33  0.75  0  1  1  0  1.0 -1  0.38  N
4  -0.33  0.67  1  1  0  0  0.8 -1  0.50  O
..   ...   ... .. .. .. ..  ... ..   ... ..
95 -1.00  0.67  1  0  0  0  1.0 -1  0.50  N
96 -1.00  0.61  1  0  0  0  0.8  0  0.50  N
97 -1.00  0.67  1  1  1  0  1.0 -1  0.31  N
98 -1.00  0.64  1  0  1  0  1.0  0  0.19  N
99 -1.00  0.69  0  1  1  0  0.6 -1  0.19  N

[100 rows x 10 columns]