<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Load-in-NumPy-(remember-to-pip-install-numpy-first)" data-toc-modified-id="Load-in-NumPy-(remember-to-pip-install-numpy-first)-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Load in NumPy (remember to pip install numpy first)</a></span></li><li><span><a href="#The-Basics" data-toc-modified-id="The-Basics-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>The Basics</a></span></li><li><span><a href="#Accessing/Changing-specific-elements,-rows,-columns,-etc" data-toc-modified-id="Accessing/Changing-specific-elements,-rows,-columns,-etc-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Accessing/Changing specific elements, rows, columns, etc</a></span></li><li><span><a href="#Initializing-Different-Types-of-Arrays" data-toc-modified-id="Initializing-Different-Types-of-Arrays-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Initializing Different Types of Arrays</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Be-careful-when-copying-arrays!!!" data-toc-modified-id="Be-careful-when-copying-arrays!!!-4.0.1"><span class="toc-item-num">4.0.1&nbsp;&nbsp;</span>Be careful when copying arrays!!!</a></span></li></ul></li></ul></li><li><span><a href="#Mathematics" data-toc-modified-id="Mathematics-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Mathematics</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Linear-Algebra" data-toc-modified-id="Linear-Algebra-5.0.1"><span class="toc-item-num">5.0.1&nbsp;&nbsp;</span>Linear Algebra</a></span></li><li><span><a href="#Statistics" data-toc-modified-id="Statistics-5.0.2"><span class="toc-item-num">5.0.2&nbsp;&nbsp;</span>Statistics</a></span></li></ul></li></ul></li><li><span><a href="#Reorganizing-Arrays" data-toc-modified-id="Reorganizing-Arrays-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Reorganizing Arrays</a></span></li><li><span><a href="#Miscellaneous" data-toc-modified-id="Miscellaneous-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Miscellaneous</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Load-Data-from-File" data-toc-modified-id="Load-Data-from-File-7.0.1"><span class="toc-item-num">7.0.1&nbsp;&nbsp;</span>Load Data from File</a></span></li><li><span><a href="#Boolean-Masking-and-Advanced-Indexing" data-toc-modified-id="Boolean-Masking-and-Advanced-Indexing-7.0.2"><span class="toc-item-num">7.0.2&nbsp;&nbsp;</span>Boolean Masking and Advanced Indexing</a></span></li></ul></li></ul></li></ul></div>

### Load in NumPy (remember to pip install numpy first)

In [3]:
import numpy as np

### The Basics

In [7]:
lista = [1,2,3]
lista

[1, 2, 3]

In [6]:
a = np.array(lista, dtype='int32')
print(a)

[1 2 3]


In [8]:
a.shape

(3,)

In [12]:
a[0]

1

In [13]:
b = np.array([[9.0,8.0,7.0,5],[6.0,5.0,4.0,5]])
print(b)

[[9. 8. 7. 5.]
 [6. 5. 4. 5.]]


In [41]:
b[1, 2:]

array([4., 5.])

In [17]:
# Get Dimension
b.ndim

2

In [18]:
# Get Shape
b.shape

(2, 4)

In [20]:
# Get Type
b.dtype

dtype('float64')

In [22]:
# Get Size
b.size

8

In [23]:
# Get total size
b.nbytes

64

In [24]:
# Get number of elements
b.size

8

### Accessing/Changing specific elements, rows, columns, etc

In [43]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [44]:
# Get a specific element [r, c]
a[1, 5]

13

In [45]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [46]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [47]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [51]:
a[0,:] = 10

In [52]:
a

array([[10, 10, 10, 10, 10, 10, 10],
       [ 0,  0,  0,  0,  0,  0,  0]])

In [48]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


*3-d example

In [29]:
b = np.array( [[[1,2],[3,4]], [[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [30]:
# Get specific element (work outside in)
b[0,1,1]

4

In [34]:
b.ndim

3

In [33]:
b.shape

(2, 2, 2)

In [35]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

In [39]:
# replace 
b[:,1,:] = [[10,10],[5,5]]

In [40]:
b

array([[[ 1,  2],
        [15, 15]],

       [[ 5,  6],
        [15, 15]]])

### Initializing Different Types of Arrays

In [53]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [55]:
# All 1s matrix
d3 = np.ones((4,2,2), dtype='int32')

In [56]:
d3

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [61]:
d3[1,:,:]= 0

In [64]:
d3

array([[[1, 1],
        [1, 1]],

       [[0, 0],
        [0, 0]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [63]:
d3[:,:,1]

array([[1, 1],
       [0, 0],
       [1, 1],
       [1, 1]], dtype=int32)

In [65]:
d3[:,:,1] = 2

In [66]:
d3

array([[[1, 2],
        [1, 2]],

       [[0, 2],
        [0, 2]],

       [[1, 2],
        [1, 2]],

       [[1, 2],
        [1, 2]]], dtype=int32)

In [60]:
d3.ndim

3

In [58]:
d3.shape

(4, 2, 2)

In [46]:
# Any other number
np.full((2,2), 11)

array([[11, 11],
       [11, 11]])

In [47]:
a

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 20, 14]])

In [48]:
# Any other number (full_like)
np.full_like(a, 0)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [49]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.46242997, 0.88351296],
       [0.87533993, 0.27578693],
       [0.68295508, 0.00333449],
       [0.65607746, 0.99449901]])

In [50]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[ 5,  0,  0],
       [ 0, -4,  6],
       [ 1, -4,  3]])

In [39]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [52]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [54]:
np.repeat(arr,5, axis=1)

array([[1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3]])

In [55]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays!!!

In [42]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]


### Mathematics

In [67]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [68]:
a + 2

array([3, 4, 5, 6])

In [69]:
a - 2

array([-1,  0,  1,  2])

In [70]:
a * 2

array([2, 4, 6, 8])

In [71]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [74]:
b = np.array([1,0,1,0])
a * b

array([1, 0, 3, 0])

In [75]:
a ** 2

array([ 1,  4,  9, 16])

In [76]:
# Take the sin
np.cos(a)



array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [51]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

##### Linear Algebra

In [58]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

nxm * mxk

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [59]:
a2 = np.full_like(a,2)

In [60]:
a2

array([[2., 2., 2.],
       [2., 2., 2.]])

In [61]:
a * a2

array([[2., 2., 2.],
       [2., 2., 2.]])

In [62]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [63]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [54]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

##### Statistics

In [78]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [79]:
np.min(stats)

1

In [80]:
np.max(stats, axis=1)

array([3, 6])

In [81]:
np.sum(stats, axis=0)

array([5, 7, 9])

### Reorganizing Arrays

In [64]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [66]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2, v1, v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [67]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous
##### Load Data from File

In [65]:
#filename = '/home/bioinformatica/Ironhack/3_Code/labs/data/01/sample_file_0.txt'

In [82]:
filedata = np.genfromtxt('data/numpy_data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


##### Boolean Masking and Advanced Indexing

In [76]:
np.where(~((filedata > 50) & (filedata < 100)), filedata, np.full_like(filedata,-1))

array([[  1,  13,  21,  11, 196,  -1,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  -1,   4,  -1,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  -1,   0,   1,   2,   9,
          8,   7,   1,  -1,  -1]], dtype=int32)